# Generated by Django 2.2.2 on 2019-06-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='games_played',
        ),
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.CharField(default=None, max_length=20000),
        ),
        migrations.AddField(
            model_name='player',
            name='draws',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals_against',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals_scored',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
