# Generated by Django 2.2.2 on 2019-06-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0002_auto_20190623_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
