# Generated by Django 2.2.2 on 2019-07-09 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0003_auto_20190709_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(to='fifa.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fixtureside',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fifa.Team'),
        ),
    ]
