# Generated by Django 2.2.2 on 2019-06-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0003_auto_20190623_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nickname',
        ),
    ]
