# Generated by Django 2.2.2 on 2019-07-09 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0004_auto_20190709_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureside',
            name='goals',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fixtureside',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fifa.Team'),
        ),
    ]
