# Generated by Django 2.2.2 on 2019-08-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0005_auto_20190709_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtureside',
            name='team_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
