# Generated by Django 2.2.2 on 2019-08-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0007_team_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='best_league_finish',
            field=models.CharField(blank=True, default='no league finish', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='best_overall_finish',
            field=models.CharField(blank=True, default='no overall finish', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tournament_appearances',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='tournament_favourite',
            field=models.CharField(blank=True, default='no favourite', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.CharField(blank=True, default='no desc', max_length=20000, null=True),
        ),
    ]
