# Generated by Django 2.2.2 on 2019-08-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0011_team_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='tv',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
