# Generated by Django 3.1.3 on 2020-12-02 04:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0006_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('played', models.BooleanField(default=False)),
                ('tv', models.CharField(choices=[('main', 'Main'), ('extra', 'Extra')], max_length=10)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('players', models.ManyToManyField(related_name='games', to='players.Player')),
            ],
            options={
                'ordering': ('-modified',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('stars', models.DecimalField(decimal_places=1, max_digits=2)),
                ('games', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='players.player')),
            ],
        ),
    ]
