# Generated by Django 3.1.3 on 2020-12-02 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='games',
            new_name='game',
        ),
    ]
