# Generated by Django 3.1.3 on 2020-12-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201202_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='goals_conceded',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_scored',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
