# Generated by Django 3.1.3 on 2020-12-01 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='players.player'),
        ),
    ]
