# Generated by Django 3.1.3 on 2020-12-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20201201_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='stars',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
