# Generated by Django 3.1.3 on 2020-12-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20201201_0101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
