# Generated by Django 3.1.4 on 2020-12-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20201204_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='goal_difference',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
